//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiletRezervasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSeferler
    {
        public int id { get; set; }
        public string IsimSoyisim { get; set; }
        public string TelefonNo { get; set; }
        public string Cinsiyet { get; set; }
        public string Nereden { get; set; }
        public string Nereye { get; set; }
        public Nullable<int> KoltukNo { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public string OtobusFirma { get; set; }
    }
}
